### ISSUE TITLE
使用该插件会导致无法刷新搜索引擎

### ISSUE THREAD

**Issue by 2451611170** [Rainsheep/halo-plugin-meilisearch#1]
用的都是默认设置，这是插件本身限制吗还是bug？
![noeng](https://github.com/Rainsheep/halo-plugin-meilisearch/assets/85246873/da2eccc0-a7e7-4a75-94db-c02d4c3401da)

**Comment by Rainsheep** [comment]
@2451611170 辛苦提供下版本信息，好久没维护了，和新版本可能有兼容性问题，周末我修复下，

**Comment by 2451611170** [comment]
> @2451611170 辛苦提供下版本信息，好久没维护了，和新版本可能有兼容性问题，周末我修复下，

插件版本1.2.0，Halo版本2.15.2
