### ISSUE TITLE
> @2451611170 辛苦提供下版本信息，好久没维护了，和新版本可能有兼容性问题，周末我修复下，

### ISSUE THREAD

**Issue by 2451611170** [Rainsheep/halo-plugin-meilisearch#2]
> @2451611170 辛苦提供下版本信息，好久没维护了，和新版本可能有兼容性问题，周末我修复下，

插件版本1.2.0，Halo版本2.15.2

_Originally posted by @2451611170 in https://github.com/Rainsheep/halo-plugin-meilisearch/issues/1#issuecomment-2139617557_

**Comment by Rainsheep** [comment]
@2451611170 更新了 docker-compose.yml 配置信息(删除可volumes 映射)，请依照 github 说明重新配置，有问题随时 call 我。
